name: Atualizar METAR e TAF

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: pip install requests

      - name: Buscar METAR e TAF
        run: python fetch_metar_taf.py

      - name: Commit e push com GitHub Pages Deploy Action
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: .
          commit-message: "Atualizar METAR e TAF"
