name: Atualizar METAR

on:
  schedule:
    - cron: '0 * * * *'  # a cada hora
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Instalar dependências
        run: pip install requests
      - name: Buscar METAR
        run: python fetch_metar.py
      - name: Commit e push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add metar.json
          git commit -m "Atualizar METAR"
          git push
